version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf       # NGINX 설정 파일
      - ./ssl:/etc/nginx/ssl                              # SSL 인증서 파일 경로
    networks:
      - the_monitor_network
    depends_on:
      - app

  app:
    image: ${DOCKER_USERNAME}/the_monitor:latest
    container_name: the_monitor-container
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - CLOUD_AWS_REGION_STATIC=${CLOUD_AWS_REGION_STATIC}
      - CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      - CLOUD_AWS_CREDENTIALS_SECRET_KEY=${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      - CLOUD_AWS_S3_BUCKET=${CLOUD_AWS_S3_BUCKET}
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE=${JWT_ACCESS_TOKEN_EXPIRE}
      - JWT_REFRESH_TOKEN_EXPIRE=${JWT_REFRESH_TOKEN_EXPIRE}
      - SPRING_DATA_REDIS_HOST=redis-server
      - SPRING_DATA_REDIS_PORT=6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_API_SEARCH_ENGINE_ID=${GOOGLE_API_SEARCH_ENGINE_ID}
      - GOOGLE_API_BASE_URL=${GOOGLE_API_BASE_URL}
    networks:
      - the_monitor_network
    expose:
      - "8080"

  redis:
    image: redis:7.0.11
    container_name: redis-server
    networks:
      - the_monitor_network
    ports:
      - "6379:6379"

networks:
  the_monitor_network:
    driver: bridge